/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

const images = [
  "https://images.unsplash.com/photo-1655219435115-d9f0faccd7cd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
  "https://images.unsplash.com/photo-1625293961325-170b642843dc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80",
  "https://images.unsplash.com/photo-1591866103793-7ec4eadcd7c5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1313&q=80",
  "https://images.unsplash.com/photo-1641733697807-8645b68d4d85?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
  "https://images.unsplash.com/photo-1654714480262-28f8a5c208d8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
  "https://images.unsplash.com/photo-1652110770901-e4a4f279951c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80",
  "https://images.unsplash.com/photo-1651600544627-56e075ef5309?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
  

]


const Home: NextPage = () => {
  const [messages, setMessages] = useState([] as string[])
  const [input, setInput] = useState('')
  
  useEffect(() => {
    document.getElementById('messageInput')?.focus()
    randomBackground()
  }, [])
  
  const randomBackground = () => {
    const randomImage = images[Math.floor(Math.random() * images.length)]
    document.body.style.backgroundImage = `url('${randomImage}')`;
  }

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInput(e.target.value)
  }

  const handleSend = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    const messageInput = document.getElementById('messageInput') as HTMLInputElement
    if(messageInput!.value.trim().length === 0) return
    setMessages([...messages, input])
    messageInput!.value = ''
    messageInput?.focus()
    setTimeout(() => {
      document.getElementById('chatMessages')?.scrollTo(0, document.getElementById('chatMessages')!.scrollHeight)
    }, 1)
    setInput('')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Soliloquy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <a className={styles.kofi} href='https://ko-fi.com/P5P35MXOQ' target='_blank' rel="noreferrer noopenner"><img src='https://cdn.ko-fi.com/cdn/kofi3.png?v=3' alt='Buy Me a Coffee at ko-fi.com' /></a>

      <main className={styles.main}>
        <header>
          <h1 className={styles.title}>Soliloquy</h1>
          <p>A place to chat alone. Tell yourself what you&apos;re feeling.</p>
        </header>

        <div className={styles.chat}>
          <section id="chatMessages" className={styles.messages}>
            {messages.map((message, key) => 
              <div key={key} className={styles.message}>{message}</div>
            )}
          </section>
          <form onSubmit={handleSend} className={styles.form}>
            <input id="messageInput" type="text" autoComplete='off' onChange={handleChange} />
            <button><i className="fa fa-paper-plane" aria-hidden="true"></i></button>
          </form>
        </div>
      </main>
      <p className={styles.unsplash}>
        <i className="fas fa-redo" onClick={randomBackground}></i>
        Background image by <a href="https://unsplash.com/" target="_blank" rel="noopener noreferrer">Unsplash</a>
      </p>
    </div>
  )
}

export default Home
